# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: v33_db
  username: v33
  password: meetupv33
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meetupv33_development

test:
  <<: *default
  database: meetupv33_test

production:
  <<: *default
  database: meetupv33_production
